#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

case "$1" in
    start)
        shift
        (bash "$SCRIPT_DIR/job-start.sh" "$@")
        ;;
    monitor)
        shift
        (bash "$SCRIPT_DIR/job-monitor.sh" "$@")
        ;;
    end)
        shift
        (bash "$SCRIPT_DIR/job-end.sh" "$@")
        ;;    
    profile)
        shift
        (bash "$SCRIPT_DIR/profile-new.sh" "$@")
        ;;            
    *)
        echo "Usage: $(basename "$0") {start|monitor|end|profile}"
        exit 1
        ;;
esac
